### ISSUE TITLE
Invalid Syntax

### ISSUE THREAD

**Issue by ghost** [cfotache/pytorch_objectdetecttrack#16]
Traceback (most recent call last):
  File "object_tracker.py", line 1, in <module>
    from models import *
  File "/home/krsbi/TA-Bill/pytorch_objectdetecttrack/models.py", line 259
    x, *losses = module[0](x, targets)
       ^
SyntaxError: invalid syntax

Can someone help me?

**Comment by cristiandatum** [comment]
Same issue with me. Any idea?

**Comment by bsharma2** [comment]
same issue

**Comment by cailinw** [comment]
For anyone still having this issue, it is because Python2 does not support this syntax. To fix the issue, please use Python3.
